// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Delivery struct {
	ID      int64
	OrderID int64
	Name    string
	Phone   string
	Zip     string
	City    string
	Address string
	Region  string
	Email   string
}

type Item struct {
	ID          int64
	OrderID     int64
	ChrtID      int64
	TrackNumber string
	Price       int32
	Rid         string
	Name        string
	Sale        int32
	Size        string
	TotalPrice  int32
	NmID        int64
	Brand       string
	Status      int32
}

type Order struct {
	ID                int64
	OrderUid          string
	TrackNumber       string
	Entry             string
	Locale            string
	InternalSignature string
	CustomerID        string
	DeliveryService   string
	Shardkey          string
	SmID              int32
	DateCreated       pgtype.Timestamp
	OofShard          string
}

type Payment struct {
	ID           int64
	OrderID      int64
	Transaction  string
	RequestID    string
	Currency     string
	Provider     string
	Amount       int32
	PaymentDt    int64
	Bank         string
	DeliveryCost int32
	GoodsTotal   int32
	CustomFee    int32
}
