// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package pg

import (
	"context"
	"time"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO delivery (
    order_id,
    name,
    phone,
    zip,
    city,
    address,
    region,
    email
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id
`

type CreateDeliveryParams struct {
	OrderID string
	Name    string
	Phone   string
	Zip     string
	City    string
	Address string
	Region  string
	Email   string
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.OrderID,
		arg.Name,
		arg.Phone,
		arg.Zip,
		arg.City,
		arg.Address,
		arg.Region,
		arg.Email,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    chrt_id,
    track_number,
    price,
    rid,
    name,
    sale,
    size,
    total_price,
    nm_id,
    brand,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id
`

type CreateItemParams struct {
	ChrtID      int64
	TrackNumber string
	Price       int32
	Rid         string
	Name        string
	Sale        int32
	Size        string
	TotalPrice  int32
	NmID        int64
	Brand       string
	Status      int32
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ChrtID,
		arg.TrackNumber,
		arg.Price,
		arg.Rid,
		arg.Name,
		arg.Sale,
		arg.Size,
		arg.TotalPrice,
		arg.NmID,
		arg.Brand,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    order_uid,
    track_number,
    entry,
    locale,
    internal_signature,
    customer_id,
    delivery_service,
    shardkey,
    sm_id,
    date_created,
    oof_shard
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id
`

type CreateOrderParams struct {
	OrderUid          string
	TrackNumber       string
	Entry             string
	Locale            string
	InternalSignature string
	CustomerID        string
	DeliveryService   string
	Shardkey          string
	SmID              int32
	DateCreated       time.Time
	OofShard          string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderUid,
		arg.TrackNumber,
		arg.Entry,
		arg.Locale,
		arg.InternalSignature,
		arg.CustomerID,
		arg.DeliveryService,
		arg.Shardkey,
		arg.SmID,
		arg.DateCreated,
		arg.OofShard,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payment (
    transaction,
    request_id,
    currency,
    provider,
    amount,
    payment_dt,
    bank,
    delivery_cost,
    goods_total,
    custom_fee
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id
`

type CreatePaymentParams struct {
	Transaction  string
	RequestID    string
	Currency     string
	Provider     string
	Amount       int32
	PaymentDt    int64
	Bank         string
	DeliveryCost int32
	GoodsTotal   int32
	CustomFee    int32
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.Transaction,
		arg.RequestID,
		arg.Currency,
		arg.Provider,
		arg.Amount,
		arg.PaymentDt,
		arg.Bank,
		arg.DeliveryCost,
		arg.GoodsTotal,
		arg.CustomFee,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDeliveryByOrderUID = `-- name: GetDeliveryByOrderUID :one
SELECT id, order_id, name, phone, zip, city, address, region, email
FROM delivery
WHERE order_id = $1
`

func (q *Queries) GetDeliveryByOrderUID(ctx context.Context, orderID string) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByOrderUID, orderID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Name,
		&i.Phone,
		&i.Zip,
		&i.City,
		&i.Address,
		&i.Region,
		&i.Email,
	)
	return i, err
}

const getItemsByTrackNumber = `-- name: GetItemsByTrackNumber :many
SELECT id, chrt_id, track_number, price, rid, name, sale, size, total_price, nm_id, brand, status
FROM items
WHERE track_number = $1
`

func (q *Queries) GetItemsByTrackNumber(ctx context.Context, trackNumber string) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItemsByTrackNumber, trackNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ChrtID,
			&i.TrackNumber,
			&i.Price,
			&i.Rid,
			&i.Name,
			&i.Sale,
			&i.Size,
			&i.TotalPrice,
			&i.NmID,
			&i.Brand,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastOrders = `-- name: GetLastOrders :many
SELECT id, order_uid, track_number, entry, locale, internal_signature, customer_id, delivery_service, shardkey, sm_id, date_created, oof_shard
FROM orders
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) GetLastOrders(ctx context.Context, limit int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, getLastOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderUid,
			&i.TrackNumber,
			&i.Entry,
			&i.Locale,
			&i.InternalSignature,
			&i.CustomerID,
			&i.DeliveryService,
			&i.Shardkey,
			&i.SmID,
			&i.DateCreated,
			&i.OofShard,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByUID = `-- name: GetOrderByUID :one
SELECT id, order_uid, track_number, entry, locale, internal_signature, customer_id, delivery_service, shardkey, sm_id, date_created, oof_shard
FROM orders
WHERE order_uid = $1
`

func (q *Queries) GetOrderByUID(ctx context.Context, orderUid string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByUID, orderUid)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderUid,
		&i.TrackNumber,
		&i.Entry,
		&i.Locale,
		&i.InternalSignature,
		&i.CustomerID,
		&i.DeliveryService,
		&i.Shardkey,
		&i.SmID,
		&i.DateCreated,
		&i.OofShard,
	)
	return i, err
}

const getPaymentByTransaction = `-- name: GetPaymentByTransaction :one
SELECT id, transaction, request_id, currency, provider, amount, payment_dt, bank, delivery_cost, goods_total, custom_fee
FROM payment
WHERE transaction = $1
`

func (q *Queries) GetPaymentByTransaction(ctx context.Context, transaction string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByTransaction, transaction)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Transaction,
		&i.RequestID,
		&i.Currency,
		&i.Provider,
		&i.Amount,
		&i.PaymentDt,
		&i.Bank,
		&i.DeliveryCost,
		&i.GoodsTotal,
		&i.CustomFee,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many

SELECT id, order_id, name, phone, zip, city, address, region, email FROM delivery
`

// =======================
// DELIVERY
// =======================
func (q *Queries) ListDeliveries(ctx context.Context) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Name,
			&i.Phone,
			&i.Zip,
			&i.City,
			&i.Address,
			&i.Region,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many

SELECT id, chrt_id, track_number, price, rid, name, sale, size, total_price, nm_id, brand, status FROM items
`

// =======================
// ITEMS
// =======================
func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ChrtID,
			&i.TrackNumber,
			&i.Price,
			&i.Rid,
			&i.Name,
			&i.Sale,
			&i.Size,
			&i.TotalPrice,
			&i.NmID,
			&i.Brand,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many

SELECT id, order_uid, track_number, entry, locale, internal_signature, customer_id, delivery_service, shardkey, sm_id, date_created, oof_shard FROM orders
`

// =======================
// ORDER
// =======================
func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderUid,
			&i.TrackNumber,
			&i.Entry,
			&i.Locale,
			&i.InternalSignature,
			&i.CustomerID,
			&i.DeliveryService,
			&i.Shardkey,
			&i.SmID,
			&i.DateCreated,
			&i.OofShard,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many

SELECT id, transaction, request_id, currency, provider, amount, payment_dt, bank, delivery_cost, goods_total, custom_fee FROM payment
`

// =======================
// PAYMENT
// =======================
func (q *Queries) ListPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Transaction,
			&i.RequestID,
			&i.Currency,
			&i.Provider,
			&i.Amount,
			&i.PaymentDt,
			&i.Bank,
			&i.DeliveryCost,
			&i.GoodsTotal,
			&i.CustomFee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
